import { Open_Sans } from "next/font/google";
import "./globals.css";

const opensan = Open_Sans({ subsets: ["latin"] });

export const metadata = {
    title: "Nguyen Minh Phong",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html className="bg-[#F9F7F7]" lang="en">
            <body className={`${opensan.className} antialiased`}>
                <header className="sticky top-0 bg-[#F9F7F7] flex justify-between sm:justify-center items-center">
                    <a href="/">
                        <img src="logo.svg" className=" h-[3rem] m-5" />
                    </a>
                    <div className="sm:hidden dropdown dropdown-bottom dropdown-end">
                        <label tabIndex={0} className="m-1">
                            <img
                                src="hamburger.svg"
                                className="w-[5rem] mr-2"
                            />
                        </label>
                        <ul
                            tabIndex={0}
                            className="dropdown-content text-white bg-[#1B0042] z-[1] menu shadow  rounded-box w-52"
                        >
                            <li>
                                <a>New</a>
                            </li>

                            <li>
                                <a>Reading list</a>
                            </li>
                            <li>
                                <a>Topics</a>
                            </li>
                            <li>
                                <div className="form-control">
                                    <input
                                        type="text"
                                        placeholder="Search"
                                        className="input input-bordered  w-[100%]"
                                    />
                                </div>
                            </li>
                            <li>
                                <a className="text-black bg-[#F9F871]">
                                    Buy me a coffee{" "}
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div
                        id="header_link"
                        className="hidden flex-1 sm:flex items-center justify-start font-semibold"
                    >
                        <a href="#" className="bg-[#FF5480] text-white">
                            Popular
                        </a>
                        <a>New</a>
                        <a>Reading list</a>
                        <a>Topics</a>
                        <a className="bg-[#F9F871]">
                            <img
                                src="coffee.svg"
                                className="h-[1rem] inline "
                            />{" "}
                            Buy me a coffee{" "}
                        </a>
                    </div>
                    <div className="hidden sm:flex justify-end items-center ml-10 ">
                        <img className="max-w-[2rem]" src="search.svg" />
                    </div>
                </header>
                <section>{children}</section>
                <div className="divider"></div>
                <footer className=" flex justify-between items-start">
                    <img
                        className="h-[2rem] hidden sm:inline "
                        src="logo.svg"
                    />
                    <div id="social_media" className=" sm:flex hidden">
                        <a>
                            <img src="zalo.svg" />
                        </a>
                        <a>
                            <img src="facebook.svg" />
                        </a>
                        <a>
                            <img src="website.svg" />
                        </a>
                        <a>
                            <img src="github.svg" />
                        </a>
                    </div>
                    <h3 className="">
                        Made with{" "}
                        <img className="h-[1rem] inline" src="heart.svg" /> by
                        Phong
                    </h3>
                </footer>
            </body>
        </html>
    );
}
